### PR TITLE
Refactor : Changing the way authentication is done

### PR DESCRIPTION
**Pull request by cupcicm**
Hello,

I would like to add a feature : being able to log in different users, that will each see their own links.
This merge request would be a first step in this direction, the next ones being :
 - Introduce warden to manage authentication
 - Introduce configuration to choose how authentication is performed (e.g with the current api-key or with something else)
 - Introduce warden-ldap to connect to an LDAP server to authenticate users 
 - Introduce per-user links in the DB
 - Show only my links in the dashboard.

I would like to know :
  1. If you are still actively maintaining this project
  2. If these changes look conceptually OK to you
  3. If you are happy about receiving / merging my commits 

Thanks, don't hesitate to tell me if you think it's not actually a good idea. Also note that I am a ruby newbie, I am doing this for fun and to learn a bit more about ruby.

Manu

### CODE REVIEW

**Comment by ariejan** [comment]
Hey @cupcicm thanks for your contributions. As a matter of fact I'm working on a complete re-write of Firefly (that is not backward compatible) that does add multi-user support (and a whole load of other things). Stay tuned for a bit and keep an eye on https://github.com/ariejan/firedragon

**Comment by nextalias** [comment]
https://github.com/ariejan/firedragon is not available to public.

**Comment by ariejan** [comment]
Yes, hence the 'stay tuned' part :-) I want to lay down the foundations before releasing it for public scrutiny.

**Comment by cupcicm** [comment]
Thanks Ariejan,

If possible, I would like to ask you a few questions :
  1. Do you have an ETA on that firedragon project ?
  2. Will it still be a Ruby/Sinatra app ? If so, are you considering using warden for authentication or something else ?

My use case is that I'd like to authenticate users using LDAP. I'd be happy to help add LDAP support to your new project. I am very close to having something that works with Sinatra + Warden + https://github.com/renewablefunding/warden-ldap in my fork.

Thanks !

**Comment by ariejan** [comment]
Hey @cupcicm,

To answer your questions:

 1. ETA is hard to say. It's not nearly finished, but I guess I could open it up this week or so.
 2. It's Rails. Although I have no authentication yet, I plan to use Devise for it, which relies on warden.

I think there's already plenty of knowledge out there of hooking devise/warden up with LDAP. I'll ping you when firedragon gets dumped into the world :-)

**Comment by ariejan** [comment]
Oh, whatever. Find the code at [ariejan/firedragon](https://github.com/ariejan/firedragon) now. Pull requests welcome!

**Comment by nextalias** [comment]
Thanks :)

**Pull request closed without merging**
